version: '3.8'

services:
  model-service:
    image: chriswyc/pytorch-cifar10-model-service:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./results:/app/results
      - ./trained_models:/app/trained_models

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cifar10db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cifar10db"]
      interval: 5s
      retries: 5

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    command: >
      sh -c "python init_db.py &&
             uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./trained_models:/app/trained_models
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/cifar10db
    depends_on:
      db:
        condition: service_healthy
      model-service:
        condition: service_started

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  

volumes:
  postgres_data: